# Defines how Dataiku applications (Application Designer) map into the generic product index
product_type: dataiku_application
source_table: base_dataiku_applications_metadata

instance_name_col: instance_name
project_key_col: project_key
key_col: application_id
name_col: application_name
subtype_col: application_kind

owner_col: owner_login
last_modified_by_col: last_modified_by_login
created_at_col: created_at
updated_at_col: updated_at

where_sql: null
