from __future__ import annotations

import logging
from dataclasses import dataclass
from pathlib import Path

# Bandit flags dynamic SQL construction (B608) below. Here, `view_name` is either
# generated by `default_view_name()` or explicitly passed by plugin code, and
# `glob` is derived from the configured managed-folder storage context.

import duckdb

from .context import StorageContext


logger = logging.getLogger(__name__)


@dataclass(frozen=True)
class ViewSpec:
    category: str
    module: str
    view_name: str


def default_view_name(*, category: str, module: str) -> str:
    return f"v_{category}__{module}".replace("-", "_")


def create_silver_view(
    *,
    conn: duckdb.DuckDBPyConnection,
    ctx: StorageContext,
    category: str,
    module: str,
    view_name: str | None = None,
) -> str:
    """Create a view over SILVER parquet for a given `{category,module}`."""

    if not ctx.bucket_or_container:
        raise ValueError("Missing bucket/container")
    if not ctx.blob_header:
        raise ValueError(f"Unsupported connection type: {ctx.connection_type}")

    view_name = view_name or default_view_name(category=category, module=module)
    root = ctx.folder_root.strip("/")
    if root:
        root = f"{root}/"
    base_path = f"{ctx.blob_header}://{ctx.bucket_or_container}/{root}silver"

    glob = f"{base_path}/category={category}/module={module}/instance_name=*/year=*/month=*/day=*/*.parquet"

    sql = f"""
    CREATE OR REPLACE VIEW {view_name} AS
    SELECT
      *,
      make_date(
        CAST(year AS INTEGER),
        CAST(month AS INTEGER),
        CAST(day AS INTEGER)
      ) AS partition_date
    FROM read_parquet(
      '{glob}',
      hive_partitioning = true,
      union_by_name = true
    );
    """.strip()  # nosec B608 (view_name and glob are plugin-controlled)

    logger.info("Creating view %s for %s/%s", view_name, category, module)
    try:
        conn.execute(sql)
    except duckdb.IOException as exc:
        # When there is no SILVER parquet yet for a given (category,module),
        # DuckDB raises an IO error. For batch builds we want to skip these
        # specs rather than fail the whole recipe.
        logger.warning("Skipping view %s (no parquet found): %s", view_name, exc)
        return ""
    return view_name
