category: datasets
module: metadata
columns:
  - instance_name
  - project_key
  - dataset_name
  - dataset_smartName
  - dataset_type
  - dataset_managed
  - dataset_featureGroup
  - dataset_typeSystemVersion
  - dataset_versionTag_versionNumber
  - dataset_versionTag_lastModifiedOn
  - dataset_versionTag_lastModifiedBy_login
  - dataset_creationTag_versionNumber
  - dataset_creationTag_lastModifiedOn
  - dataset_creationTag_lastModifiedBy_login
  #- run_timestamp
  #- extras