canonical_capabilities_table:
  description: >
    Small table to cache the canonical_capabilities tags into a single place for reuse
  depends_on:
    - usage_events_view
  sql: |
    CREATE OR REPLACE TABLE canonical_capabilities_base AS
    SELECT DISTINCT
        canonical_capability,
        dataiku_category
    FROM usage_events_view
    WHERE canonical_capability <> 'NON_CORE'
    ORDER BY
        canonical_capability,
        dataiku_category;