raw_view: |
  CREATE OR REPLACE VIEW {table_name} AS
  SELECT *
  FROM read_parquet(
    {paths},
    hive_partitioning = true
  );
usage_events_raw: |
  CREATE OR REPLACE VIEW usage_events_raw_view AS
  SELECT *
  FROM read_parquet(
    '{parquet_path}',
    hive_partitioning = true
  )
  WHERE dataiku_category IS NOT NULL;
usage_events: |
  CREATE OR REPLACE VIEW usage_events_view AS
  SELECT 
    *,
    CASE
      WHEN dataiku_category IN (
        'PROJECTS', 'FLOW', 'DATASET', 'FOLDERS', 'WIKI_ARTICAL_DISCUSSIONS'
      ) THEN 'PROJECT_MAINTENANCE'

      WHEN dataiku_category IN (
        'VISUAL_RECIPES','PREPARE','MISC_RECIPES','CODING'
      ) THEN 'DATA_ENGINEERING'

      WHEN dataiku_category IN (
        'STATISTIC_ANALYTICS','MLOPS'
      ) THEN 'ADVANCED_ANALYTICS_ML'

      WHEN dataiku_category IN (
        'AUTOMATION','SCENARIOS','DEPLOYER'
      ) THEN 'AUTOMATION_ORCHESTRATION'

      WHEN dataiku_category IN (
        'APPLICATION_DESIGNER','WEBAPPS', 'CHARTS_DASHBOARD'
      ) THEN 'DATA_DELIVERY'

      WHEN dataiku_category = 'APIS'
        THEN 'APIS_INTEGRATION'

      WHEN dataiku_category = 'GENAI_LLM'
        THEN 'GENAI_LLM'

      ELSE 'NON_CORE'
    END AS canonical_capability
  FROM usage_events_raw_view;
