# BLOB SETUP FOR AWS, AZURE, GCS
blob_setup:
  aws_modules: INSTALL httpfs; LOAD httpfs;
  aws_headers_assume: |
    CREATE OR REPLACE SECRET duckdb_s3_secret (
      TYPE s3, 
      KEY_ID '{key_id}',
      SECRET '{secret}',
      SESSION_TOKEN '{token}',
      REGION '{aws_region}'
    )
  aws_headers_static: |
    CREATE OR REPLACE SECRET duckdb_s3_secret (
      TYPE s3,
      KEY_ID '{key_id}',
      SECRET '{secret}',
      REGION '{aws_region}'
    );
  azure_modules: INSTALL azure; LOAD azure;
  azure_oauth2_headers: |
    CREATE OR REPLACE SECRET duckdb_az_secret (
      TYPE azure,
      PROVIDER service_principal,
      TENANT_ID '{tenant_id}',
      CLIENT_ID '{client_id}',
      CLIENT_SECRET '{client_secret}',
      ACCOUNT_NAME '{account_name}'
    )
  azure_access_key_headers: |
    CREATE OR REPLACE SECRET duckdb_az_secret (
      TYPE azure,
      PROVIDER access_key,
      ACCOUNT_NAME '{account_name}',
      ACCESS_KEY '{access_key}'
    );
  gcp_modules: INSTALL httpfs; LOAD httpfs;
  gcp_headers: |
    CREATE OR REPLACE SECRET duckdb_gs_secret (
        TYPE gcs,
        KEY_ID '{hmac_id}',
        SECRET '{hmac_secret}'
    )