raw_view: |
  CREATE OR REPLACE VIEW {table_name} AS
  SELECT
    {select_clause},
    year,
    month,
    day,
    make_date(
      CAST(year AS INTEGER),
      CAST(month AS INTEGER),
      CAST(day AS INTEGER)
    ) AS partition_date
  FROM read_parquet(
    '{base_path}/category={category}/module={module}/instance_name=*/year=*/month=*/day=*/*.parquet',
    hive_partitioning = true
  )
  ;